import 'dart:typed_data';

/// Nintendo disc "junk" generator: a lagged Fibonacci generator (f=xor, j=32,
/// k=521) used by RVZ to store scrubbed padding as a 68-byte seed instead of the
/// raw bytes. Port of Dolphin's `LaggedFibonacciGenerator`.
///
/// Output is the buffer's little-endian byte image, matching Dolphin on the
/// little-endian targets this app ships to (x64, arm64).
class LaggedFibonacciGenerator {
  static const _k = 521;
  static const _j = 32;
  static const _seedWords = 17; // SEED_SIZE

  final Uint32List _buf = Uint32List(_k);
  late final Uint8List _bytes = _buf.buffer.asUint8List();
  int _pos = 0; // byte position within _buf

  /// [seed] is 68 bytes (17 big-endian u32).
  LaggedFibonacciGenerator(Uint8List seed) {
    final sd = ByteData.sublistView(seed);
    for (var i = 0; i < _seedWords; i++) {
      _buf[i] = sd.getUint32(i * 4, Endian.big);
    }
    // Fill the rest with the raw recurrence (no transform yet).
    for (var i = _seedWords; i < _k; i++) {
      _buf[i] =
          ((_buf[i - 17] << 23) ^ (_buf[i - 16] >> 9) ^ _buf[i - 1]) & 0xffffffff;
    }
    // Then transform and byteswap every word once, so the little-endian byte
    // image of the buffer is the output stream (Dolphin's Initialize does the
    // "shift by 18" fixup here to keep GetBytes a plain memcpy).
    for (var i = 0; i < _k; i++) {
      final x = _buf[i];
      _buf[i] = _swap32((x & 0xff00ffff) | ((x >> 2) & 0x00ff0000));
    }
    for (var i = 0; i < 4; i++) {
      _advance();
    }
  }

  static int _swap32(int x) =>
      ((x & 0xff) << 24) |
      ((x & 0xff00) << 8) |
      ((x >> 8) & 0xff00) |
      ((x >> 24) & 0xff);

  // The k=521, j=32 lagged-fibonacci state update; resets the read position.
  // The k=521, j=32 lagged-fibonacci state update. Does NOT touch the read
  // position — callers manage that (matches Dolphin's Forward()).
  void _advance() {
    for (var i = 0; i < _j; i++) {
      _buf[i] ^= _buf[i + _k - _j];
    }
    for (var i = _j; i < _k; i++) {
      _buf[i] ^= _buf[i - _j];
    }
  }

  /// Advances the generator by [count] bytes without emitting them.
  void forward(int count) {
    _pos += count;
    while (_pos >= _k * 4) {
      _advance();
      _pos -= _k * 4;
    }
  }

  /// Writes [count] generated bytes into [out] starting at [outOffset].
  void getBytes(int count, Uint8List out, int outOffset) {
    var done = 0;
    while (done < count) {
      final avail = _k * 4 - _pos;
      final take = (count - done) < avail ? (count - done) : avail;
      out.setRange(outOffset + done, outOffset + done + take, _bytes, _pos);
      _pos += take;
      done += take;
      if (_pos == _k * 4) {
        _advance();
        _pos = 0;
      }
    }
  }
}
